sudo: false
language: python
python: '3.6'
branches:
  except:
  - gh-pages
install:
- pip install tox "setuptools>=28.2"
- python setup.py -q build
- python setup.py -q install
- python setup.py -q publish
script: pytest
deploy:
  provider: pypi
  distributions: sdist --formats=zip bdist_wheel
  user: bspruth
  password:
    secure: KTuw1CQz+XXojogHAmMTOG81C64MVf/rkAc7RDFfZtWvvf9hJ/4Qeft+F6UtNRyJ981mzL9IU5+kEqUOSLL6kd326qIIeykudpnweLfhIR4phOQkTWRPpqFdmC0Nepi6iVjIxwHFzr7pK8TTc8UaSIfwMgT999AAuZuLqs6s+0786NA6h58+dnWULQyu8WVY2ZXriw2FCfau6j+7AGAI1CuSRgUSDVkVBs08rMgzPpn3+bHcNcPXpybL+VFkh4FLL2GLkVfO4F5+duAzgHZkpEXIKS/LAlqT5df5n2Eyc1xw7VxM96V4yAi8w4Uvcpjn0YQs1Xo5GDdVQeb4tF+C5HgGy5q7PAoQp9ghdtmn76GdHrycX8jHw5o0iqJjSejMfF3CXuUGZ9zhGVO9IGLI/qMErV4fd/J0pbqDljVl/Y6b3zon2KJtZ6+iSR7eTHY1XpEWMAQG2dJJm9FWGz+rSvzImeiHFRoAoZ6DOd0rgF03n97ZJxYWlUoK8KatQGXXqzx1k4SZJmGII+he7U7RbP/ibV+/ri4wvJSNM0Jcf0apuokD5tHy1j8LW4oQGg95s2vwwVwSoIZApppagHaW1W1Xz1bAq2klaY7vIsFFdF4XARRkjxy3hf0M6BcRmYHHPj+w6rgJgxQb3Np9X8YbFcffC97TO/YMvo4Ueel3U20=
  skip_upload_docs: true
  on:
    tags: true
    branch: master
    repo: target/fortifyapi
