sudo: false
language: python
python:
  - "2.7"
  - "3.6"
  - "nightly"

branches:
  except:
    - gh-pages
    
install:
  - python setup.py -q build
  - python setup.py -q install
  
# command to run tests
script: pytest
  
